# Generated by Django 4.2.5 on 2023-10-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_products_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AlterField(
            model_name='products',
            name='tagline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
