# Generated by Django 4.2.5 on 2023-11-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_products_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='tagline',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
