# Generated by Django 4.2.5 on 2023-11-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_brand_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='poster',
            field=models.FileField(blank=True, help_text='High res backgound image. landscape. Preferably light coloured', null=True, upload_to='uploads/brands/posters'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/brands/logos'),
        ),
    ]
