# Generated by Django 4.2.5 on 2024-03-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_remove_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='dark_background',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='poster',
            field=models.FileField(blank=True, help_text='High res backgound image. landscape.', null=True, upload_to='uploads/brands/posters'),
        ),
    ]
