# Generated by Django 4.2.5 on 2024-03-20 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_offer_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='percentage_discount',
            new_name='discount_percentage',
        ),
    ]
