# Generated by Django 4.2.5 on 2024-03-20 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_rename_percentage_discount_offer_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.offer'),
        ),
    ]
