# Generated by Django 4.2.5 on 2024-03-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_cart_discounted_price_cart_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
